name: Publish BaseOS Docker Image

defaults:
  run:
    shell: bash
env:
  TZ: Asia/Shanghai
  PNAME: baseos

on:
  workflow_dispatch:
    inputs:
      JDK_TAG:
        description: 'Image Tag'
        required: true
        type: choice
        options:
          - 'jdk-11'
          - 'jdk-17'
          - 'jdk-21'
          - 'jdk-25'
        default: 'jdk-17'
      IMAGE_BASE:
        description: 'Base Image'
        required: true
        type: choice
        options:
          - 'almalinux'
          - 'anolisos'
        default: 'almalinux'


jobs:
  multi-arch:
    name: Publish BaseOS Docker Image With ${{ inputs.JDK_TAG }}
    env:
      JDK_TAG: ${{ inputs.JDK_TAG }}
      IMAGE_BASE: ${{ inputs.IMAGE_BASE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker build meta with ${{ env.PNAME }}
        id: tags
        run: |
          echo REPO_NAME=${{ vars.DOCKER_REPO }}/$PNAME >> $GITHUB_ENV
          echo "IMAGE_TAG=${{env.IMAGE_BASE}}-${{ env.JDK_TAG }}" >> $GITHUB_ENV

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
        #with:
        #  buildkitd-flags: --debug

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and push with ${{ env.IMAGE_TAG }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/deps
          file: ${{ github.workspace }}/baseos/Dockerfile.${{ env.IMAGE_BASE }}
          target: prod
          build-args: |
            JDK_TAG=${{ env.JDK_TAG }}
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.REPO_NAME }}:${{ env.JDK_TAG }}
          push: true
          provenance: false
          #no-cache: true