name: Test Easysearch Integration

defaults:
  run:
    shell: bash

env:
  DNAME: agent
  PNAME: easysearch
  TZ: Asia/Shanghai
  TOKEN: ${{ secrets.X_TOKEN }}
  PRE_RELEASE: ${{ vars.PRE_RELEASE }}
  RELEASE_URL: ${{ vars.RELEASE_URL }}
  PUBLISH_RELEASE: ${{ vars.PUBLISH_RELEASE }}
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION }}
  JAVA_VERSION: ${{ vars.JAVA_VERSION }}
  GRADLE_VERSION: ${{ vars.GRADLE_VERSION }}
  SSH_GIT_REPO: ${{ secrets.SSH_GIT_REPO }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
  OSS_EP: ${{ secrets.OSS_EP }}
  OSS_AK: ${{ secrets.OSS_AK }}
  OSS_SK: ${{ secrets.OSS_SK }}
  OSS_BK: ${{ secrets.OSS_BK }}
  OSS_MODE: ${{ secrets.OSS_MODE }}
  LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
  LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
  CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
  CONNECT_PORT: ${{ secrets.CONNECT_PORT }}
  CONNECT_KEY: ${{ secrets.CONNECT_KEY }}
  CONNECT_TIMEOUT: ${{ vars.CONNECT_TIMEOUT }}
  CONNECT_MODE: ${{ vars.CONNECT_MODE }}
  CONNECT_METHOD: ${{ secrets.CONNECT_METHOD }}
  PROXY_RELEASE_INFINILABS: ${{ secrets.PROXY_RELEASE_INFINILABS }}
  PUBLISH_VERSION: ${{ inputs.PUBLISH_VERSION || vars.EASYSEARCH_PUBLISH_VERSION }}
  ZULU_JAVA_VERSION: ${{ vars.ZULU_JAVA_VERSION }}
  JAVA_VERSION_21: ${{ vars.JAVA_VERSION_21 }}
  NODEJS_VERSION: ${{ vars.NODEJS_EXT_VERSION }}
  PNPM_VERSION: "latest"

on:
  schedule:
    - cron: "30 16 * * *"
  workflow_dispatch:
    inputs:
      PUBLISH_VERSION:
        description: "Publish Version"
        required: false
        default: "2.0.3"

jobs:
  publish:
    name: Publish easysearch files and docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup bootstrap
        uses: ./containers/bootstrap

      - name: Set up and check env
        run: |
          mkdir -p $GITHUB_WORKSPACE/{dest,jdks}
          # Set GRADLE version and BRANCH based on PUBLISH_VERSION
          BRANCH="1.x"
          if [[ "$PUBLISH_VERSION" == 2.* ]]; then
            BRANCH="main"
            GRADLE_VERSION=${{ vars.GRADLE_VERSION_8 }}
            JAVA_VERSION=${{ vars.JAVA_VERSION_21 }}
          fi
          echo "JAVA_VERSION=$JAVA_VERSION â†’ using gradle version: $GRADLE_VERSION for branch: $BRANCH"
          echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "GRADLE_VERSION=$GRADLE_VERSION" >> $GITHUB_ENV

      - name: Run connect in background
        run: |
          connect -c "$GITHUB_WORKSPACE/.net.json" >/dev/null 2>&1 &
          echo "Connect started with pid $!"
          sleep 5

      - name: Set up java toolchain
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up gradle
        run: |
          if [[ ! -d "$HOME/gradle-$GRADLE_VERSION" ]]; then
            wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip -P $HOME
            cd $HOME && unzip -q gradle-$GRADLE_VERSION-bin.zip && rm -rf gradle-$GRADLE_VERSION-bin.zip
          fi
          echo "PATH=$HOME/gradle-$GRADLE_VERSION/bin:$PATH" >> $GITHUB_ENV
          echo Gradle path is $HOME/gradle-$GRADLE_VERSION

      - name: Checkout ${{ env.PNAME }} repo
        run: |
          git clone --depth 1 --branch "$BRANCH" $SSH_GIT_REPO/$PNAME $GITHUB_WORKSPACE/$PNAME

      - name: Set up with pnpm toolchain
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up nodejs toolchain
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Check nodejs toolchain
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            npm install -g pnpm
          fi
          node -v && npm -v && pnpm -v
      - name: Cache Gradle packages and jdks
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            /root/.gradle/caches
            ${{ github.workspace }}/jdks
          key: java-toolchian-${{ runner.os }}-gradle-${{ env.JAVA_DISTRIBUTION }}-${{ env.JAVA_VERSION }}

      - name: Prepare for build dependency
        run: |
          cd $GITHUB_WORKSPACE/$PNAME && echo Checkout $PNAME repo $(git log -1 --pretty=format:"%h, %ad" --date=iso)
          $GITHUB_WORKSPACE/products/$PNAME/init-release.sh
          echo "Testing with easysearch version: $PUBLISH_VERSION"
          echo "STEP_VERSION=$PUBLISH_VERSION" >> $GITHUB_ENV
          PLUGIN_HOME=$GITHUB_WORKSPACE/$PNAME/plugins
          echo "PLUGIN_HOME=$PLUGIN_HOME" >> $GITHUB_ENV

      - name: Run Rest tests
        continue-on-error: true
        timeout-minutes: 10
        run: |
          cd $GITHUB_WORKSPACE/$PNAME
          gradle clean :rest-api-spec:yamlRestTest --tests org.easysearch.test.rest.ClientYamlTestSuiteIT -Dtest.jvmArgs=-Xmx4g -Dtests.heap.size=2g -Drest.suite=rest-api-spec/src/yaml/rest-api/ -Drest.blacklist=rest-api-spec/src/yaml/rest-api/blacklist.txt -Deasysearch.version=$STEP_VERSION --info --stacktrace
      
      - name: Run Security tests
        continue-on-error: true
        timeout-minutes: 10
        run: |
          cd $GITHUB_WORKSPACE/$PNAME
          gradle clean :modules:security:test -Dtest.jvmArgs=-Xmx4g -Dtests.heap.size=2g --tests com.infinilabs.security.dlic.rest.api.AccountApiTest --tests com.infinilabs.security.HttpIntegrationTests --tests com.infinilabs.security.dlic.rest.api.RolesApiTest --tests com.infinilabs.security.ssl.rest.RestGetSSLCertificatesActionTests --rerun-tasks --info

      - name: Run IndexingPressureIT tests
        continue-on-error: true
        timeout-minutes: 10
        run: |
          cd $GITHUB_WORKSPACE/$PNAME
          gradle :server:clean :server:internalClusterTest -Dtest.jvmArgs=-Xmx4g -Dtests.heap.size=2g --tests org.easysearch.indexingpressure.IndexingPressureIT --tests org.easysearch.index.IndexingPressureIT -Dtests.heap.size=2g -Dtests.cluster.reroute.timeout=300s -Dtests.cluster.recovery.timeout=300s -Dtests.cluster.stabilization.timeout=300s --rerun-tasks --info
          # Copy test reports
          mkdir -p $GITHUB_WORKSPACE/all-test-reports/indexing-pressure
          cp -r $GITHUB_WORKSPACE/$PNAME/server/build/reports/tests/internalClusterTest/* $GITHUB_WORKSPACE/all-test-reports/indexing-pressure || true

      - name: Run Read old lucene index tests
        continue-on-error: true
        timeout-minutes: 10
        run: |
          cd $GITHUB_WORKSPACE/$PNAME
          gradle :server:test -Dtest.jvmArgs=-Xmx4g -Dtests.heap.size=2g --tests org.easysearch.index.engine.InternalEngineTests --tests org.easysearch.index.store.StoreTests --rerun-tasks --info
          # Copy test reports
          mkdir -p $GITHUB_WORKSPACE/all-test-reports/read-old-lucene-index
          cp -r $GITHUB_WORKSPACE/$PNAME/server/build/reports/tests/test/* $GITHUB_WORKSPACE/all-test-reports/read-old-lucene-index || true

      - name: Run Rules Plugin Compiler tests
        continue-on-error: true
        timeout-minutes: 10
        env:
          RULE_DB_HOME: ${{env.PLUGIN_HOME}}/rules/ruledb-pkg
          LD_LIBRARY_PATH: ${{env.PLUGIN_HOME}}/rules/ruledb-pkg/lib:${{env.LD_LIBRARY_PATH}}
          PATH: ${{env.PLUGIN_HOME}}/rules/ruledb-pkg/bin:${{env.PATH}} 
        run: |
          cd $GITHUB_WORKSPACE/$PNAME
          gradle clean :plugins:rules:test -Dtest.jvmArgs=-Xmx4g -Dtests.heap.size=2g --tests org.easysearch.rules.compiler.RuleCompilerTests --rerun-tasks --info
          # Copy test reports
          mkdir -p $GITHUB_WORKSPACE/all-test-reports/rules-plugin
          cp -r $GITHUB_WORKSPACE/$PNAME/plugins/rules/build/reports/tests/test/* $GITHUB_WORKSPACE/all-test-reports/rules-plugin || true

      - name: Run Rules Plugin Multi-Node IT tests
        continue-on-error: true
        timeout-minutes: 10
        env:
          RULE_DB_HOME: ${{env.PLUGIN_HOME}}/rules/ruledb-pkg
          LD_LIBRARY_PATH: ${{env.PLUGIN_HOME}}/rules/ruledb-pkg/lib:${{env.LD_LIBRARY_PATH}}
          PATH: ${{env.PLUGIN_HOME}}/rules/ruledb-pkg/bin:${{env.PATH}} 
        run: |
          cd $GITHUB_WORKSPACE/$PNAME
          gradle clean :plugins:rules:internalClusterTest -Dtest.jvmArgs=-Xmx4g -Dtests.heap.size=2g --tests org.easysearch.rules.sync.RulesMultiNodeIT --rerun-tasks --info
           # Copy test reports
          mkdir -p $GITHUB_WORKSPACE/all-test-reports/rules-plugin-multi-node
          cp -r $GITHUB_WORKSPACE/$PNAME/plugins/rules/build/reports/tests/internalClusterTest/* $GITHUB_WORKSPACE/all-test-reports/rules-plugin-multi-node || true
      
      - name: Upload Test Reports
        if: always() 
        uses: actions/upload-artifact@v6
        with:
          name: all-test-reports
          path: all-test-reports/
          retention-days: 7

  notify_on_failure:
    runs-on: ubuntu-latest
    needs: [publish]
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Notify message via feishu
        env:
          FEISHU_BOT_URL: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_NAME: ${{ github.workflow }}
          RUN_ID: ${{ github.run_id }}
          ACTOR: ${{ github.triggering_actor }}
          SERVER_URL: ${{ github.server_url }}
        run: $GITHUB_WORKSPACE/scripts/feishu_message.sh